"""
OpenClaw Gateway Server — Configuration

Runs on your EC2 instance.  Accepts inbound WebSocket connections
from laptop agents and provides an HTTP API + CLI for dispatching
action requests.

SECURITY: Load AUTH_TOKEN from environment in production.
"""

import os

# ---------------------------------------------------------------------------
# Network
# ---------------------------------------------------------------------------
WS_HOST: str = "0.0.0.0"
WS_PORT: int = 8765

HTTP_HOST: str = "127.0.0.1"   # HTTP API listens on loopback only
HTTP_PORT: int = 8766

# ---------------------------------------------------------------------------
# TLS — paths to cert/key generated by setup_tls.sh
# ---------------------------------------------------------------------------
TLS_CERT: str = os.environ.get(
    "OPENCLAW_TLS_CERT",
    os.path.join(os.path.dirname(__file__), "certs", "server.crt"),
)
TLS_KEY: str = os.environ.get(
    "OPENCLAW_TLS_KEY",
    os.path.join(os.path.dirname(__file__), "certs", "server.key"),
)

# ---------------------------------------------------------------------------
# Authentication — must match the token configured on the laptop agent
# ---------------------------------------------------------------------------
AUTH_TOKEN: str = os.environ.get("OPENCLAW_AUTH_TOKEN", "")

# ---------------------------------------------------------------------------
# Timeouts
# ---------------------------------------------------------------------------
# How long to wait for an agent response before timing out (seconds).
ACTION_TIMEOUT_SECONDS: int = 120

# WebSocket keep-alive.
WS_PING_INTERVAL: int = 30
WS_PING_TIMEOUT: int = 10

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_LEVEL: str = os.environ.get("OPENCLAW_LOG_LEVEL", "INFO")
